[[gateway]]
name="SIGINT Bridge Gateway"
enable=true

[[gateway.inout]]
account="discord.compsoc"
channel="ID:359905927643791360" # sigint

[[gateway.inout]]
account="discord.sigint"
channel="ID:754018502058180664" # general

[[gateway]]
name="SIGINT Announcement Bridge Gateway"
enable=true

[[gateway.out]]
account="discord.compsoc"
channel="ID:359905927643791360" # sigint

[[gateway.in]]
account="discord.sigint"
channel="ID:754018502058180662" # announcements

[[gateway]]
name="GameDevSIG Bridge Gateway"
enable=true

[[gateway.inout]]
account="discord.compsoc"
channel="ID:730146239315837052" # gamedevsig

[[gateway.inout]]
account="discord.gamedevsig"
channel="ID:1018832521519173642" # general

[[gateway]]
name="Project Share Bridge Gateway"
enable=true

[[gateway.inout]]
account="discord.compsoc"
channel="ID:1130422421015498804" # project-share

[[gateway.inout]]
account="discord.projectshare"
channel="ID:1075737869915799564" # general

[discord]
[discord.compsoc]

Server="315277951597936640" # CompSoc Edinburgh
RemoteNickFormat="{NICK}"
# Disable threading, as Webhooks can't reply to threads and it looks off
PreserveThreading=false
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true

[discord.sigint]

Server="754018502058180659" # SIGINT Edinburgh
RemoteNickFormat="{NICK}"
# Disable threading, as Webhooks can't reply to threads and it looks off
PreserveThreading=false
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true

[discord.gamedevsig]

Server="1010126395403419648" # GameDevSIG
RemoteNickFormat="{NICK}"
# Disable threading, as Webhooks can't reply to threads and it looks off
PreserveThreading=false
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true

[discord.projectshare]

Server="1075737869446025247" # Project Share
RemoteNickFormat="{NICK}"
# Disable threading, as Webhooks can't reply to threads and it looks off
PreserveThreading=false
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true
