[[gateway]]
name="one Gateway"
enable=true

[[gateway.inout]]
account="discord.compsoc"
channel="ID:316038111811600387" # bottest

[[gateway.inout]]
account="discord.sigint"
channel="ID:480720731638857770" # bottest2

[discord]
[discord.compsoc]

# You can get your token by following the instructions on
# https://github.com/42wim/matterbridge/wiki/Discord-bot-setup
# in particular that the "Members Intent" checkbox is important.
# If you want roles/groups mentions to be shown with names instead of ID, 
# you'll need to give your bot the "Manage Roles" permission.
Server="315277951597936640" # CompSoc Edinburgh
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
RemoteNickFormat="{NICK} ({BRIDGE})"
# Map threads from other bridges on discord replies
PreserveThreading=true
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true

[discord.sigint]

Server="315277951597936640" # CompSoc Edinburgh
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
RemoteNickFormat="{NICK} ({GATEWAY})"
# Map threads from other bridges on discord replies
PreserveThreading=true
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true
