# Definitions for the various gateway configurations. See lower down for
# account configurations.

[[gateway]]
name="SIGINT Bridge Gateway"
enable=true

[[gateway.inout]]
account="discord.compsoc"
channel="ID:359905927643791360" # sigint

[[gateway.inout]]
account="discord.sigint"
channel="ID:754018502058180664" # general

[[gateway]]
name="SIGINT Announcement Bridge Gateway"
enable=true

[[gateway.out]]
account="discord.compsoc"
channel="ID:359905927643791360" # sigint

[[gateway.in]]
account="discord.sigint"
channel="ID:754018502058180662" # announcements

[[gateway]]
name="GameDevSIG Bridge Gateway"
enable=true

[[gateway.inout]]
account="discord.compsoc"
channel="ID:730146239315837052" # gamedevsig

[[gateway.inout]]
account="discord.gamedevsig"
channel="ID:1018832521519173642" # general

[[gateway]]
name="Project Share Bridge Gateway"
enable=true

[[gateway.inout]]
account="discord.compsoc"
channel="ID:1130422421015498804" # project-share

[[gateway.inout]]
account="discord.projectshare"
channel="ID:1075737869915799564" # general

[[gateway]]
name="TypeSig Bridge Gateway"
enable=true

[[gateway.inout]]
account="discord.compsoc"
channel="ID:1156637304211906713" # typesig

[[gateway.inout]]
account="discord.typesig"
channel="ID:1157074727794380811" # general

[[gateway]]
name="TypeSig Announcement Bridge Gateway"
enable=true

[[gateway.out]]
account="discord.compsoc"
channel="ID:1156637304211906713" # typesig

[[gateway.in]]
account="discord.typesig"
channel="ID:1157074584361771028" # announcements

[[gateway]]
# This 'name' field is used by the connecting Minecraft plugin to identify the gateway.
name="Minecraft_Vanilla_Server_Bridge_Gateway"
enable=true

[[gateway.inout]]
# As required by https://github.com/Programie/MatterBukkit
account="api.matterbukkit"
channel="api"

[[gateway.inout]]
account="discord.compsoc-mcavatars"
channel="ID:1245849017565446254" # minecraft-ingame


# Definitions for the various account configurations

[discord]
[discord.compsoc]

Server="315277951597936640" # CompSoc Edinburgh
RemoteNickFormat="{NICK}"
# Disable threading, as Webhooks can't reply to threads and it looks off
PreserveThreading=false
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true

# Goal: Show minecraft avatars for MC -> Discord messages. We want to use the
# IconURL setting, but this setting can only be applied on account level, not
# per gateway (a bit stupid ngl, we should be able to change settings for each
# inout gateway). So, we need to create a separate account definition that
# has all-identical settings, except for IconURL.
[discord.compsoc-mcavatars]

Server="315277951597936640" # CompSoc Edinburgh
RemoteNickFormat="{NICK}"
# Disable threading, as Webhooks can't reply to threads and it looks off
PreserveThreading=false
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true
IconURL="https://mc-heads.net/avatar/{NICK}.png"

[discord.sigint]

Server="754018502058180659" # SIGINT Edinburgh
RemoteNickFormat="{NICK}"
# Disable threading, as Webhooks can't reply to threads and it looks off
PreserveThreading=false
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true

[discord.gamedevsig]

Server="1010126395403419648" # GameDevSIG
RemoteNickFormat="{NICK}"
# Disable threading, as Webhooks can't reply to threads and it looks off
PreserveThreading=false
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true

[discord.projectshare]

Server="1075737869446025247" # Project Share
RemoteNickFormat="{NICK}"
# Disable threading, as Webhooks can't reply to threads and it looks off
PreserveThreading=false
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true

[discord.typesig]

Server="1157074271877746750" # TypeSig
RemoteNickFormat="{NICK}"
# Disable threading, as Webhooks can't reply to threads and it looks off
PreserveThreading=false
# Allow no mentions, since it can be source of spam. Default is all.
AllowMention=[]
# Automatically manage webhooks for Discord channels
AutoWebhooks=true
# Show a preview of other bot's embeds by copying the title and description
ShowEmbeds=true

[api]

# Used for the Matterbukkit Minecraft Spigot plugin to connect from.
# Make sure the port is exposed on the Docker container.
[api.matterbukkit]

BindAddress="0.0.0.0:4242"
Buffer=1000
RemoteNickFormat="d┅{NICK}"
